### PR TITLE
Handle empty data frame in `Athena_write_table()`

### LINKED ISSUE #200: Can't write/append an empty data frame
``` r
con <- ...

noctua::noctua_options()
df <- data.frame(x = integer())

DBI::dbWriteTable(con, "test_df", df)
#> INFO: Special characters "\t" has been converted to " " to help with Athena reading file format tsv
#> Error in seq.default(1, max_row, as.integer(max.batch)): invalid '(to - from)/by'
```

<sup>Created on 2023-05-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by mgirlich**
Fixes #200.

### CODE REVIEW

**Comment by DyfanJones** [comment]
Really appreciate the PR @mgirlich. I will take a closer look over it, to see why it failed the codecov :)

**Comment by DyfanJones** [comment]
I wonder if we could get away with something simpler. To upload an empty dataframe we only need to create the ddl. Athena will return the empty table if there is no data in AWS S3 location. 🤔 

```sql
CREATE EXTERNAL TABLE `iris`(
  `sepal_length` double, 
  `sepal_width` double, 
  `petal_length` double, 
  `petal_width` double, 
  `species` string)
ROW FORMAT DELIMITED 
  FIELDS TERMINATED BY '\t' 
  LINES TERMINATED BY '\n' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  's3://my-bucket/iris'
TBLPROPERTIES (
  'compressionType'='gzip', 
  'skip.header.line.count'='1',)
```

```sql
select * from iris
```

Screenshot 2023-05-23 at 18 05 12

Hmmm I wonder how this will work with hive partitioning 🤔  Will have to try it out

**Comment by mgirlich** [comment]
I have no idea why codecov failed. I'm pretty optimistic that my test covers this use case 😄  Might have to do with `skip_if_no_env()`?

**Comment by DyfanJones** [comment]
It looks like this PR is currently failing.

``` r
library(DBI)

con <- dbConnect(noctua::athena(), rstudio_conn_tab = F)

dbWriteTable(con, "remove_iris", iris[0,])
#> INFO: data.frame colnames have been converted to align with Athena DDL naming convertions: 
#> Sepal_Length,
#> Sepal_Width,
#> Petal_Length,
#> Petal_Width
#> INFO: Special characters "\t" has been converted to " " to help with Athena reading file format tsv
#> Error in file(con, "rb"): invalid 'description' argument
```

<sup>Created on 2023-05-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I think we will have to do a little more work to get this working :)

**Comment by DyfanJones** [comment]
> I have no idea why codecov failed. I'm pretty optimistic that my test covers this use case 😄 Might have to do with `skip_if_no_env()`?

Possibly, I will update the skip to check if it is the case

**Comment by DyfanJones** [comment]
hmmm the github action has failed i am not sure why but i did some testing locally and it looks like it worked fine :) I will merge this and raise a separate PR to resolve the Github action

**Pull request merged**
